### PR TITLE
Add SDL Keyboard adaptation

### PR DESCRIPTION
**Pull request by FASTSHIFT**
Added key input support for SDL emulators.

### CODE REVIEW

**Comment by Vogtinator** [comment]
Hi and thanks for your PR!

I actually had a branch locally which is similar to this, I just never pushed it because it needed some cleanup...

I pushed it here now: https://github.com/Vogtinator/crafti/pull/26/files

Compared to this PR it doesn't need a lookup table (it just assigns sdl keys to t_key) and introduces an SDL event loop with frame limiter and some mouse support. Does that work for you or is something missing?

**Comment by FASTSHIFT** [comment]
> Hi and thanks for your PR!
> 
> I actually had a branch locally which is similar to this, I just never pushed it because it needed some cleanup...
> 
> I pushed it here now: https://github.com/Vogtinator/crafti/pull/26/files
> 
> Compared to this PR it doesn't need a lookup table (it just assigns sdl keys to t_key) and introduces an SDL event loop with frame limiter and some mouse support. Does that work for you or is something missing?

Can we abstract input into a separate interface? This can avoid modifying the underlying source code, and no SDL related code will appear in the game code.

**Comment by FASTSHIFT** [comment]
This is the [SDL2 abstraction layer](https://github.com/FASTSHIFT/lv_gba_emu/blob/main/port/gba_port_sdl2.c) of my [GBA emulator](https://github.com/FASTSHIFT/lv_gba_emu). It uses the callback function `read_cb` for decoupling, making it easy to port to any platform.

**Comment by FASTSHIFT** [comment]
The frame limiter can be made dynamic rather than having a fixed sleep time, because the complexity of the game scene may change and the rendering time will change accordingly.

**Pull request closed without merging**
